#!/bin/bash
COUNTER=1
while(true) do
 ./start
curl "https://api.telegram.org/bot338678192:AAEmDiPzM8HBEssScI1aPHRQIJB5_fb1HA0/sendmessage" -F "chat_id=-1001108991032" -F "text=TabLiqGar NOW RUNNING"
let COUNTER=COUNTER+1 
done
